package com.celeste.databases.storage.model.entity;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter(AccessLevel.PROTECTED)
@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
public abstract class ForwardingConnection implements Connection {

  private final Connection connection;

  @Override
  public Statement createStatement() throws SQLException {
    return connection.createStatement();
  }

  @Override
  public Statement createStatement(final int type, final int concurrency) throws SQLException {
    return connection.createStatement(type, concurrency);
  }

  @Override
  public Statement createStatement(final int type, final int concurrency, final int holdability)
      throws SQLException {
    return connection.createStatement(type, concurrency, holdability);
  }

  @Override
  public Clob createClob() throws SQLException {
    return connection.createClob();
  }

  @Override
  public NClob createNClob() throws SQLException {
    return connection.createNClob();
  }

  @Override
  public Blob createBlob() throws SQLException {
    return connection.createBlob();
  }

  @Override
  public SQLXML createSQLXML() throws SQLException {
    return connection.createSQLXML();
  }

  @Override
  public Struct createStruct(final String typeName, final Object[] attributes)
      throws SQLException {
    return connection.createStruct(typeName, attributes);
  }

  @Override
  public Array createArrayOf(final String typeName, final Object[] elements) throws SQLException {
    return connection.createArrayOf(typeName, elements);
  }

  @Override
  public PreparedStatement prepareStatement(final String sql) throws SQLException {
    return connection.prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(final String sql, final int autoGeneratedKeys)
      throws SQLException {
    return connection.prepareStatement(sql, autoGeneratedKeys);
  }

  @Override
  public PreparedStatement prepareStatement(final String sql, final String[] names)
      throws SQLException {
    return connection.prepareStatement(sql, names);
  }

  @Override
  public PreparedStatement prepareStatement(final String sql, final int[] indexes)
      throws SQLException {
    return connection.prepareStatement(sql, indexes);
  }

  @Override
  public PreparedStatement prepareStatement(final String sql, final int type,
      final int concurrency) throws SQLException {
    return connection.prepareStatement(sql, type);
  }

  @Override
  public PreparedStatement prepareStatement(final String sql, final int type,
      final int concurrency, int holdability) throws SQLException {
    return connection.prepareStatement(sql, type, concurrency, holdability);
  }

  @Override
  public CallableStatement prepareCall(final String sql) throws SQLException {
    return connection.prepareCall(sql);
  }

  @Override
  public CallableStatement prepareCall(final String sql, final int type, final int concurrency)
      throws SQLException {
    return connection.prepareCall(sql, type, concurrency);
  }

  @Override
  public CallableStatement prepareCall(final String sql, final int type, final int concurrency,
      final int holdability) throws SQLException {
    return connection.prepareCall(sql, type, concurrency, holdability);
  }

  @Override
  public Savepoint setSavepoint() throws SQLException {
    return connection.setSavepoint();
  }

  @Override
  public Savepoint setSavepoint(final String name) throws SQLException {
    return connection.setSavepoint(name);
  }

  @Override
  public String nativeSQL(final String sql) throws SQLException {
    return connection.nativeSQL(sql);
  }

  @Override
  public boolean isValid(final int timeout) throws SQLException {
    return connection.isValid(timeout);
  }

  @Override
  public void commit() throws SQLException {
    connection.commit();
  }

  @Override
  public void abort(final Executor executor) throws SQLException {
    connection.abort(executor);
  }

  @Override
  public void rollback() throws SQLException {
    connection.rollback();
  }

  @Override
  public void rollback(final Savepoint savepoint) throws SQLException {
    connection.rollback(savepoint);
  }

  @Override
  public void releaseSavepoint(final Savepoint savepoint) throws SQLException {
    connection.releaseSavepoint(savepoint);
  }

  @Override
  public DatabaseMetaData getMetaData() throws SQLException {
    return connection.getMetaData();
  }

  @Override
  public Map<String, Class<?>> getTypeMap() throws SQLException {
    return connection.getTypeMap();
  }

  @Override
  public void setTypeMap(final Map<String, Class<?>> map) throws SQLException {
    connection.setTypeMap(map);
  }

  @Override
  public String getCatalog() throws SQLException {
    return connection.getCatalog();
  }

  @Override
  public void setCatalog(final String catalog) throws SQLException {
    connection.setCatalog(catalog);
  }

  @Override
  public Properties getClientInfo() throws SQLException {
    return connection.getClientInfo();
  }

  @Override
  public String getClientInfo(final String name) throws SQLException {
    return connection.getClientInfo(name);
  }

  @Override
  public void setClientInfo(final Properties properties) throws SQLClientInfoException {
    connection.setClientInfo(properties);
  }

  @Override
  public void setClientInfo(final String name, final String value) throws SQLClientInfoException {
    connection.setClientInfo(name, value);
  }

  @Override
  public String getSchema() throws SQLException {
    return connection.getSchema();
  }

  @Override
  public void setSchema(final String schema) throws SQLException {
    connection.setSchema(schema);
  }

  @Override
  public int getTransactionIsolation() throws SQLException {
    return connection.getTransactionIsolation();
  }

  @Override
  public void setTransactionIsolation(final int level) throws SQLException {
    connection.setTransactionIsolation(level);
  }

  @Override
  public int getHoldability() throws SQLException {
    return connection.getHoldability();
  }

  @Override
  public void setHoldability(final int holdability) throws SQLException {
    connection.setHoldability(holdability);
  }

  @Override
  public int getNetworkTimeout() throws SQLException {
    return connection.getNetworkTimeout();
  }

  @Override
  public void setNetworkTimeout(final Executor executor, final int milliseconds)
      throws SQLException {
    connection.setNetworkTimeout(executor, milliseconds);
  }

  @Override
  public boolean getAutoCommit() throws SQLException {
    return connection.getAutoCommit();
  }

  @Override
  public void setAutoCommit(final boolean autoCommit) throws SQLException {
    connection.setAutoCommit(autoCommit);
  }

  @Override
  public boolean isReadOnly() throws SQLException {
    return connection.isReadOnly();
  }

  @Override
  public void setReadOnly(final boolean readOnly) throws SQLException {
    connection.setReadOnly(readOnly);
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return connection.getWarnings();
  }

  @Override
  public void clearWarnings() throws SQLException {
    connection.clearWarnings();
  }

  @Override
  public <T> T unwrap(final Class<T> face) throws SQLException {
    return connection.unwrap(face);
  }

  @Override
  public boolean isWrapperFor(final Class<?> face) throws SQLException {
    return connection.isWrapperFor(face);
  }

  @Override
  public void close() throws SQLException {
    connection.close();
  }

  @Override
  public boolean isClosed() throws SQLException {
    return connection.isClosed();
  }

}
